<h4>Muslim Friendly Tourism</h4>
        <p class="w3-text-grey">Beberapa tahun terakhir, Korea Selatan jadi salah satu tujuan wisata favorit para pelancong untuk berlibur. Kini pun semakin banyak agen travel yang menawarkan jasa open trip jalan-jalan murah ke Negeri Ginseng ini atau sekadar tiket murah ke sana. Khususnya bagi para pecinta budaya Korea, pasti kamu punya impian untuk berkunjung ke negaranya para idol ini kan? Nah, tak sekadar memajukan tempat wisatanya. Korea Selatan kini juga semakin sering mempromosikan kulinernya yang sungguh menggiurkan kalau kita nonton di KDrama. Dan seiring semakin banyaknya muslim traveler yang berkunjung ke sana, semakin menjamur juga lho restoran-restoran halal di sana! Tentu ini kabar baik buat para wisatawan muslim, ya! </p>
        <p class="w3-text-grey">Buat kamu yang muslim dan masih ragu buat kulineran di Korea, jangan khawatir! Nih, ada beberapa rekomendasi restoran yang muslim-friendly di kawasan Seoul, Korea Selatan yang bisa kamu cicipi.</p>

        <p> 1. Busan Jib Restaurant</p>
        <p class="w3-text-grey"> Berlokasi di kawasan Myeongdong, Seoul, restoran Busan Jib ini menyajikan hidangan asli Korea lho. Di sini kamu bisa menikmati hidangan spicu chicken stew dan ginseng chicken-nya yang jadi andalan. Selain itu, kalau kamu ingin makan wrap alias ssam ala drama-drama Korea, di Busan Jib juga bisa. Tenang, dagingnya pakai daging sapi kok! Restoran ini tidak menyediakan babi maupun olahan lainnya. Untuk harga makanannya berada di kisaran 8.000-10.000 won. </p>
        <p>2. Osegyehyang Vegetarian Restaurant</p>
        <p class="w3-text-grey">Ohsegehyang Restaurant berada di kawasan Insadong, Seoul, Korea Selatan. Kawasan ini terkenal sebagai kompleks restoran tradisional Korea. Nah, karena hanya menyajikan menu vegetarian sehingga makanan di sini insyaAllah muslim friendly. Restoran ini jadi salah satu restoran vegetarian terbaik dan terlaris lho! Makan di sini, kamu perlu mengeluarkan kocek minimal 15.000 won. Selain makanan utama, tentu saja disajikan juga side dish khas Korea. 
        <p> 3. Halal Kitchen Korea</p>
        <p class="w3-text-grey"> Restoran yang satu ini unik lho, karena bangunannya menggunakan hanok yang merupakan rumah tradisional Korea. Menu makanan yang direkomendasikan di sini adalah tteokbokki-nya. Sedangkan makanan yang jadi andalan dan jelas akan membuatmu kenyang di antaranya bulgogi, yanggalbi, dan dakgalbi. Serunya lagi, di sini juga disediakan musala lho. Jadi kalau kamu ke sini pas jam salat, bisa sekalian beribadah juga. Meski belum memiliki sertifikat halal resmi dari Korean Halal Federation, namun restoran ini dimiliki oleh seorang muslim.</p>
        <p> 4. EID – 이드 Halal Korean Food</p>
        <p class="w3-text-grey">Kalau restoran satu ini sudah jamak diketahui muslim traveler lho. Maka, kamu wajib banget ngicipin makan di EID Restaurant yang berlokasi di Usadan-ro, Yongsan-gu, Seoul. Makan di sini kamu tak perlu khawatir lagi dengan kehalalannya karena EID sudah mengantongi sertifikat halal dari Korea Muslim Federation. Serunya lagi, restoran ini dekat dengan masjid juga. Beberapa menu yang siap menggoyang lidahmu adalah beef bulgogi dengan harga kisaran 10.000 won, haemul deop bap alias seafood stir-fried dengan harga 12.000 won, jja jjang bap seharga 8.000 won, dan samgyetang yang nikmat banget disantap saat musim panas.</p>
        <p> 5. Kampungku Restaurant</p>
        <p class="w3-text-grey">Berada di kawasan Myeongdong, Seoul, Kampungku Restaurant ini didirikan oleh Mr. Farid Hakim asal Malaysia lho! Yang unik adalah, Kampungku Restaurant menyajikan hidangan pizza dengan topping dishes khas Korea lho! Salah satunya adalah bulgogi pizza. Buat kamu yang suka keju, juga ada nih rekomendasi pizza Deluxe Cheese yang enak banget! 
        <p> 6. Korean BBQ at Yang Good</p>
        <p class="w3-text-grey">Kalau habis jalan-jalan di kawasan Gangnam, sempatkan makan di sini. Barbeque yang disajikan di sini adalah daging ayam, daging domba, dan daging sapi. Namun, mungkin kamu perlu berhati-hati karena di sini juga disajikan minuman alkohol. Tak cuma BBQ, kamu juga bisa menikmati lamb soup, deonjang-jjigae, atau mulnaengmyeon jika kamu berkunjung saat musim panas. Harga menunya di sini mungkin cukup pricey, ya. Kamu harus menyiapkan uang paling tidak 11.000-20.000 won untuk bisa menikmati BBQ ala Korea di sini.
        <p> 7. Makan Halal Korean Restaurant (Itaewon)</p>
        <p class="w3-text-grey">Hampir mirip dengan EID Restaurant, Makan Halal Korean Restaurant sudah mengantongi sertifikat halal juga lho. Restoran yang berlokasi di Itaewon, Seoul ini berdiri sejak tahun 2015. Menu andalannya di antaranya adalah bulgogi, dakdoritang, mulnaengmyeon (mi dingin khas Korea), dan masih banyak lagi. Harganya pun cukup terjangkau. Kamu perlu menyiapkan uang 8.000-15.000 won makan di sini. Tapi, restoran ini tutup setiap hari Selasa, jadi pastikan kamu datang di hari lainnya ya!</p>